In [ ]:
import torch
import torchvision.transforms.functional as TF, torch.nn.functional as F

/home/fmussari/mambaforge/envs/fastaiv3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [ ]:
preds1 = torch.tensor([[0.,2.,5.,8.], [-5.,-2.,5.,-8.], [-2.5,-3.,2.,8.]])
preds2 = torch.tensor([[0.,-2.,-5.,-8.], [5.,-2.,4.,-8.], [2.5,-2.1,-4.,-8.3]])
preds3 = torch.tensor([[-0.58,-2.5,-3.5,-8.], [-5.,2.,-4.,-8.], [-2.5,2.,4.,-8.3]])
preds4 = torch.tensor([[-0.58,-2.5,-3.5,5.], [-5.,2.,-4.,3.], [-2.5,2.,4.,3]])
preds5 = torch.tensor([[-0.58,2.5,-3.5,1.], [-5.,2.,-4.,1.], [2.5,2.,2.,3]])
preds1.shape, preds2.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
lista_preds = [preds1, preds2, preds3, preds4, preds5]

In [ ]:
lista_preds

[tensor([[ 0.0000,  2.0000,  5.0000,  8.0000],
         [-5.0000, -2.0000,  5.0000, -8.0000],
         [-2.5000, -3.0000,  2.0000,  8.0000]]),
 tensor([[ 0.0000, -2.0000, -5.0000, -8.0000],
         [ 5.0000, -2.0000,  4.0000, -8.0000],
         [ 2.5000, -2.1000, -4.0000, -8.3000]]),
 tensor([[-0.5800, -2.5000, -3.5000, -8.0000],
         [-5.0000,  2.0000, -4.0000, -8.0000],
         [-2.5000,  2.0000,  4.0000, -8.3000]]),
 tensor([[-0.5800, -2.5000, -3.5000,  5.0000],
         [-5.0000,  2.0000, -4.0000,  3.0000],
         [-2.5000,  2.0000,  4.0000,  3.0000]]),
 tensor([[-0.5800,  2.5000, -3.5000,  1.0000],
         [-5.0000,  2.0000, -4.0000,  1.0000],
         [ 2.5000,  2.0000,  2.0000,  3.0000]])]

In [ ]:
lista_targets = [
    torch.tensor([[0.,0.,0.,1.], [0.,1.,0.,0.], [0.,0.,1.,0.]]),
    torch.tensor([[0.,0.,1.,0.], [0.,0.,1.,0.], [1.,0.,0.,0.]]),
    torch.tensor([[1.,0.,0.,0.], [0.,0.,1.,0.], [0.,1.,0.,0.]]),
    torch.tensor([[0.,0.,0.,1.], [0.,0.,0.,1.], [0.,0.,0.,1.]]),
    torch.tensor([[0.,1.,0.,0.], [0.,1.,0.,0.], [1.,0.,0.,0.]])
]

In [ ]:
preds = torch.cat(lista_preds, dim=0)
preds

tensor([[ 0.0000,  2.0000,  5.0000,  8.0000],
        [-5.0000, -2.0000,  5.0000, -8.0000],
        [-2.5000, -3.0000,  2.0000,  8.0000],
        [ 0.0000, -2.0000, -5.0000, -8.0000],
        [ 5.0000, -2.0000,  4.0000, -8.0000],
        [ 2.5000, -2.1000, -4.0000, -8.3000],
        [-0.5800, -2.5000, -3.5000, -8.0000],
        [-5.0000,  2.0000, -4.0000, -8.0000],
        [-2.5000,  2.0000,  4.0000, -8.3000],
        [-0.5800, -2.5000, -3.5000,  5.0000],
        [-5.0000,  2.0000, -4.0000,  3.0000],
        [-2.5000,  2.0000,  4.0000,  3.0000],
        [-0.5800,  2.5000, -3.5000,  1.0000],
        [-5.0000,  2.0000, -4.0000,  1.0000],
        [ 2.5000,  2.0000,  2.0000,  3.0000]])

In [ ]:
targets = torch.cat(lista_targets, dim=0)
targets

tensor([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]])

In [ ]:
targets.shape

torch.Size([15, 4])

In [ ]:
targets[:,:]

tensor([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]])

In [ ]:
target_lst = targets.unique(dim=0).tolist()
target_lst

[[0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0]]

In [ ]:
(torch.tensor([0., 0., 0., 1.]).expand(15, 4)==targets).all(dim=1)

tensor([ True, False, False, False, False, False, False, False, False,  True,
         True,  True, False, False, False])

In [ ]:
u,v = targets.shape
tar_index = {}

for k in targets.unique(dim=0):
    print(k)
    tar_index[k] = (k.expand(u, v)==targets).all(dim=1).nonzero().flatten()
tar_index

tensor([0., 0., 0., 1.])
tensor([0., 0., 1., 0.])
tensor([0., 1., 0., 0.])
tensor([1., 0., 0., 0.])


{tensor([0., 0., 0., 1.]): tensor([ 0,  9, 10, 11]),
 tensor([0., 0., 1., 0.]): tensor([2, 3, 4, 7]),
 tensor([0., 1., 0., 0.]): tensor([ 1,  8, 12, 13]),
 tensor([1., 0., 0., 0.]): tensor([ 5,  6, 14])}

In [ ]:
ta = torch.tensor( [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,5,7,8,9,10,12,34] )
u = ta.shape
u

torch.Size([23])

In [ ]:
ta_index = {}
for k in ta.unique(dim=0):
    ta_index[k]=(ta==k).nonzero().flatten()
ta_index

{tensor(0): tensor([0]),
 tensor(1): tensor([1]),
 tensor(2): tensor([2]),
 tensor(3): tensor([3]),
 tensor(4): tensor([4]),
 tensor(5): tensor([ 5, 16]),
 tensor(6): tensor([6]),
 tensor(7): tensor([ 7, 17]),
 tensor(8): tensor([ 8, 18]),
 tensor(9): tensor([ 9, 19]),
 tensor(10): tensor([10, 20]),
 tensor(11): tensor([11]),
 tensor(12): tensor([12, 21]),
 tensor(13): tensor([13]),
 tensor(14): tensor([14]),
 tensor(15): tensor([15]),
 tensor(34): tensor([22])}

In [ ]:
losses = F.cross_entropy(preds, targets, reduce=False)

In [ ]:
losses

tensor([5.1265e-02, 7.0010e+00, 6.0025e+00, 5.1331e+00, 1.3139e+00, 1.1509e-02,
        1.8327e-01, 6.0034e+00, 2.1283e+00, 4.5189e-03, 3.1417e-01, 1.4086e+00,
        2.4025e-01, 3.1574e-01, 1.3511e+00])

In [ ]:
tar_losses = {}

for k,indcs in tar_index.items():
    tar_losses[k]=losses[indcs]
tar_losses

{tensor([0., 0., 0., 1.]): tensor([0.0513, 0.0045, 0.3142, 1.4086]),
 tensor([0., 0., 1., 0.]): tensor([6.0025, 5.1331, 1.3139, 6.0034]),
 tensor([0., 1., 0., 0.]): tensor([7.0010, 2.1283, 0.2403, 0.3157]),
 tensor([1., 0., 0., 0.]): tensor([0.0115, 0.1833, 1.3511])}

In [ ]:
tar_losses_top = {}
for k,indcs in tar_index.items():
    tar_losses_top[k] = torch.topk(losses[indcs], losses[indcs].shape[0]).indices
    
tar_losses_top

{tensor([0., 0., 0., 1.]): tensor([3, 2, 0, 1]),
 tensor([0., 0., 1., 0.]): tensor([3, 0, 1, 2]),
 tensor([0., 1., 0., 0.]): tensor([0, 1, 3, 2]),
 tensor([1., 0., 0., 0.]): tensor([2, 1, 0])}

In [ ]:
sampler_top_losses = torch.topk(losses, preds.shape[0]).indices
sampler_top_losses

tensor([ 1,  7,  2,  3,  8, 11, 14,  4, 13, 10, 12,  6,  0,  5,  9])

In [ ]:
self_epoch = 2
self_n = { 0: 0, 1: 0.21, 2: 0.42, 3: 0.21, 4: 0 }

self_num_samples = sampler_top_losses.size(0)
print(f'{self_num_samples=}')

n = int(self_n[self_epoch] * self_num_samples)
print(f'{n=}')

inverted_losses_for_epochs = torch.flip(
    torch.tensor(sampler_top_losses.clone().detach()[:n]), dims=(0,)
).cpu()

inverted_losses_for_epochs

self_num_samples=15
n=6


/tmp/ipykernel_219/1020001491.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(sampler_top_losses.clone().detach()[:n]), dims=(0,)


tensor([11,  8,  3,  2,  7,  1])

In [ ]:
sampler_top_losses[-n:], sampler_top_losses, inverted_losses_for_epochs

(tensor([6, 0, 5]), tensor([1, 7, 2, 3, 8, 4, 6, 0, 5]), tensor([2, 7, 1]))

In [ ]:
# epoch=0
rand_tensor = torch.randperm(self_num_samples).tolist()
self_data_indexes_for_epoch = rand_tensor
self_data_indexes_for_epoch

[1, 4, 0, 2, 6, 7, 8, 3, 5]

In [ ]:
# epoch=2
rand_tensor = torch.randperm(self_num_samples).tolist()

self_data_indexes_for_epoch = torch.tensor(self_data_indexes_for_epoch)
self_data_indexes_for_epoch[sampler_top_losses[-n:]], self_data_indexes_for_epoch[inverted_losses_for_epochs]

(tensor([8, 1, 7]), tensor([0, 3, 4]))

In [ ]:
self_data_indexes_for_epoch[sampler_top_losses[-n:]] = self_data_indexes_for_epoch[inverted_losses_for_epochs]
self_data_indexes_for_epoch

tensor([2, 3, 5, 4, 0, 3, 5, 2, 7])

In [ ]:
self_data_indexes_for_epoch = self_data_indexes_for_epoch[rand_tensor]
self_data_indexes_for_epoch

tensor([7, 4, 3, 0, 2, 5, 3, 5, 2])

In [ ]:
print(torch.tensor([0,2,6])[[1,2,0]])
print(torch.tensor([1,3,4])[[0,1,2]])
print(torch.tensor([5,7,8])[[0,2,1]])

tensor([2, 6, 0])
tensor([1, 3, 4])
tensor([5, 8, 7])


In [ ]:
t = torch.tensor([0,2,6,8,10,16,80,10,12,45,56])
torch.cat((t[:4], t[-4:]))

tensor([ 0,  2,  6,  8, 10, 12, 45, 56])

In [ ]:
torch.cat((t[:4], torch.tensor([])))

tensor([0., 2., 6., 8.])

## DataLoaders

In [ ]:
from torch.utils.data import DataLoader, WeightedRandomSampler

In [ ]:
list(WeightedRandomSampler([0.9, 0.4, 0.05, 0.2, 0.3, 0.1], 3, replacement=False))

[0, 4, 3]

In [ ]:
xb = torch.rand(20,1,8,8)

preds = torch.rand(20,10)
yb = torch.tensor([0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9])
xb.shape, preds.shape, yb.shape

(torch.Size([20, 1, 8, 8]), torch.Size([20, 10]), torch.Size([20]))

In [ ]:
F.cross_entropy(preds, yb, reduction='none')

tensor([1.7730, 1.9653, 2.3778, 2.3921, 1.8411, 2.2324, 2.2041, 2.6778, 2.3053,
        2.8118, 2.0552, 2.6604, 2.1511, 2.4199, 2.5745, 2.4360, 2.1496, 2.0577,
        2.5092, 2.3182])

In [ ]:
y_idxs = {}
for k in yb.unique(dim=0):
    y_idxs[k.item()] = (k==yb).nonzero().flatten()
y_idxs

{0: tensor([0, 1]),
 1: tensor([2, 3]),
 2: tensor([4, 5]),
 3: tensor([6, 7]),
 4: tensor([8, 9]),
 5: tensor([10, 11]),
 6: tensor([12, 13]),
 7: tensor([14, 15]),
 8: tensor([16, 17]),
 9: tensor([18, 19])}

In [ ]:
xb[y_idxs[0]]

tensor([[[[0.2199, 0.6844, 0.9007, 0.9883, 0.8702, 0.9252, 0.2161, 0.3935],
          [0.6095, 0.0276, 0.4560, 0.7161, 0.1244, 0.4482, 0.5051, 0.5468],
          [0.8307, 0.1041, 0.0755, 0.2139, 0.0549, 0.4479, 0.1585, 0.5211],
          [0.6367, 0.5379, 0.2095, 0.2638, 0.3813, 0.0326, 0.8070, 0.1358],
          [0.5473, 0.3918, 0.3578, 0.7544, 0.2588, 0.7535, 0.8684, 0.8103],
          [0.5645, 0.1820, 0.9003, 0.5122, 0.1426, 0.2379, 0.1581, 0.8038],
          [0.9921, 0.9871, 0.8713, 0.9484, 0.9409, 0.9681, 0.4653, 0.6030],
          [0.7469, 0.0494, 0.9577, 0.5373, 0.7264, 0.0448, 0.8434, 0.5295]]],


        [[[0.8422, 0.3031, 0.8413, 0.3961, 0.9903, 0.7293, 0.7609, 0.9512],
          [0.5877, 0.9824, 0.0316, 0.6535, 0.0636, 0.9349, 0.6246, 0.2327],
          [0.7969, 0.4418, 0.3323, 0.8367, 0.1864, 0.7162, 0.9746, 0.5567],
          [0.3780, 0.7475, 0.4777, 0.3243, 0.3557, 0.9951, 0.4380, 0.6525],
          [0.2108, 0.2133, 0.3818, 0.3585, 0.0771, 0.9863, 0.9056, 0.9800],
        

In [ ]:
xb[y_idxs[0]].shape

torch.Size([2, 1, 8, 8])

In [ ]:
xb[:1]

tensor([[[[0.2199, 0.6844, 0.9007, 0.9883, 0.8702, 0.9252, 0.2161, 0.3935],
          [0.6095, 0.0276, 0.4560, 0.7161, 0.1244, 0.4482, 0.5051, 0.5468],
          [0.8307, 0.1041, 0.0755, 0.2139, 0.0549, 0.4479, 0.1585, 0.5211],
          [0.6367, 0.5379, 0.2095, 0.2638, 0.3813, 0.0326, 0.8070, 0.1358],
          [0.5473, 0.3918, 0.3578, 0.7544, 0.2588, 0.7535, 0.8684, 0.8103],
          [0.5645, 0.1820, 0.9003, 0.5122, 0.1426, 0.2379, 0.1581, 0.8038],
          [0.9921, 0.9871, 0.8713, 0.9484, 0.9409, 0.9681, 0.4653, 0.6030],
          [0.7469, 0.0494, 0.9577, 0.5373, 0.7264, 0.0448, 0.8434, 0.5295]]]])

In [ ]:
xb1 = torch.rand(20,1,8,8)
xb2 = torch.rand(10,1,8,8)

xb3 = torch.cat((xb1, xb2))
xb3.shape

torch.Size([30, 1, 8, 8])

In [ ]:
xb = torch.rand(30,1,8,8)

preds = torch.rand(20,10)
yb = torch.tensor([1,9,1,0,2,3,8,3,4,2,7,5,6,7,5,0,8,4,9,0,9,8,7,0,5,4,3,1,2,6])
xb.shape, preds.shape, yb.shape

(torch.Size([30, 1, 8, 8]), torch.Size([20, 10]), torch.Size([30]))

In [ ]:
(yb==0).nonzero().flatten()

tensor([ 3, 15, 19, 23])

In [ ]:
unique_counts = yb.unique(dim=0, return_counts=True)
unique_counts[0], unique_counts[1]

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([4, 3, 3, 3, 3, 3, 2, 3, 3, 3]))

In [ ]:
targ_idxs = []
for k in yb.unique(dim=0):
    targ_idxs.append((yb==k).nonzero().flatten())

torch.stack(targ_idxs)[0], torch.stack(targ_idxs)[1]

RuntimeError: stack expects each tensor to be equal size, but got [4] at entry 0 and [3] at entry 1

In [ ]:
targ_idxs = torch.tensor()
for k in yb.unique(dim=0):
    targ_idxs = torch.append((yb==k).nonzero().flatten())

torch.stack(targ_idxs)[0], torch.stack(targ_idxs)[1]

### Understanding Curriculum Learning
As tweaked from tommyc's version from ...

In [ ]:
from typing import Iterator
from torch.utils.data import DataLoader, WeightedRandomSampler

In [ ]:
losses = torch.rand(5)
top_losses = torch.topk(losses, 5).indices
losses, top_losses, torch.flip(top_losses, dims=(0,))

(tensor([0.4008, 0.7320, 0.5781, 0.7409, 0.9445]),
 tensor([4, 3, 1, 2, 0]),
 tensor([0, 2, 1, 3, 4]))

In [ ]:
epochs = 5
# Porcentaje a sustituir en cada epoch
self_n = { 0: 0, 1: 0.21, 2: 0.42, 3: 0.21, 4: 0 }

# Supongamos un set de 256 losses

batch_sz = 256
dataset_sz = batch_sz*30

rand_tensor_0 = torch.randperm(dataset_sz).tolist()

losses = torch.rand(dataset_sz)
top_losses = torch.topk(losses, dataset_sz).indices

In [ ]:
top_losses[:5], top_losses[-5:], top_losses[-1612:-1611]

(tensor([ 659, 5513, 2833, 2567, 3390]),
 tensor([4633, 1122, 1848, 7656, 7386]),
 tensor([1907]))

In [ ]:
inverted_losses_for_epochs = torch.flip(top_losses, dims=(0,))
inverted_losses_for_epochs[:5], inverted_losses_for_epochs[-5:]

(tensor([7386, 7656, 1848, 1122, 4633]),
 tensor([3390, 2567, 2833, 5513,  659]))

In [ ]:
data_indexes_for_epoch = torch.tensor(rand_tensor_0)

In [ ]:
epoch=1
rand_tensor_1 = torch.randperm(dataset_sz).tolist()
n = int(self_n[epoch] * dataset_sz)
print(n)

# índices de imagenes con las n menores pérdidas
data_indexes_for_epoch[ top_losses[-n:] ]

1612


In [ ]:
data_indexes_for_epoch[ top_losses[-n:] ] = data_indexes_for_epoch[ top_losses[:n] ]

In [ ]:
im_idx, im_count = data_indexes_for_epoch.unique(dim=0, return_counts=True)

(im_count>1).sum()

tensor(1612)

In [ ]:
a=[1,0,3,5]
sorted(a)

[0, 1, 3, 5]

In [ ]:
a

[1, 0, 3, 5]

In [ ]:
w = [2 for _ in range(100)] + [1 for _ in range(100)]

In [ ]:
wrs = torch.tensor(list(WeightedRandomSampler(weights=w, num_samples=100, replacement=True)))

wrs.unique(dim=0, return_counts=True)

(tensor([  2,   3,   6,   7,   8,   9,  10,  13,  15,  16,  17,  21,  26,  27,
          29,  32,  34,  36,  38,  39,  42,  44,  45,  46,  55,  56,  57,  58,
          63,  64,  67,  74,  75,  78,  80,  81,  83,  84,  85,  88,  90,  91,
          93,  94,  96,  98, 104, 107, 113, 123, 125, 126, 130, 135, 136, 139,
         141, 143, 152, 154, 156, 157, 159, 162, 163, 172, 175, 178, 181, 185,
         189, 190, 191, 193, 197, 198]),
 tensor([2, 1, 2, 1, 1, 2, 1, 1, 1, 3, 3, 2, 3, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1,
         2, 1, 3, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
         1, 1, 1, 1]))

In [ ]:
class CustomTrainingSampler(WeightedRandomSampler):
    def __init__(self, *args, **kwargs):
        WeightedRandomSampler.__init__(self, *args, **kwargs)
        self._idxs_for_epoch = []
        
    def __iter__(self) -> Iterator[int]:
        self._idxs_for_epoch = list(range(100))
        
        yield from self._idxs_for_epoch


In [ ]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, start, end):
        super(MyIterableDataset).__init__()
        assert end > start, "this example code only works with end >= start"
        self.start = start
        self.end = end
    
    def __len__(self):
        return len(range(self.start, self.end))
        
    def __getitem__(self, index):
        return list(range(self.start, self.end))[index]

ds = MyDataset(start=0, end=10)

In [ ]:
len(ds)

10

In [ ]:
print(list(torch.utils.data.DataLoader(ds, num_workers=0)))

[tensor([0]), tensor([1]), tensor([2]), tensor([3]), tensor([4]), tensor([5]), tensor([6]), tensor([7]), tensor([8]), tensor([9])]


In [ ]:
print(list(DataLoader(ds, 2)))

[tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9])]


In [ ]:
num_samples=100

ds = MyDataset(start=0, end=num_samples)

sampler=CustomTrainingSampler(weights=[1 for _ in range(num_samples)], num_samples=num_samples)

list(DataLoader(ds, 10, sampler=sampler))

[tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 tensor([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 tensor([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 tensor([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 tensor([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 tensor([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 tensor([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]